project:
  name: Ackee
  shortName: ackee
  url: https://ackee.electerious.com/
  description: Self-hosted analytics tool for those who care about privacy
repository:
  url: https://phaoll.github.io/charts/ # temporary changes for test purposes
  name: ackee
chart:
  name: ackee
release:
  name: ackee-release
  namespace: ackee